### ISSUE TITLE
Pages do not set context

### ISSUE THREAD

**Issue by mudrd8mz** [narinkaew/moodle-local_innoedtools#2]
Please make sure to develop plugins with developer debugging on. Visiting either Inno Smart Report or Inno Smart Portfolio producing a valid debugging warning: "This page did not call $PAGE->set_url(...)."

**Comment by narinkaew** [comment]
Fixed, latest commits on May 20, 2017. 
https://github.com/narinkaew/moodle-local_innoedtools/commit/094fb98931f17e97364b7c73aa46e81527204a32

- Enable developer debugging
- Add $PAGE->set_url on every pages
