### ISSUE TITLE
Dangerous usage of course ID numbers as SQL identifier

### ISSUE THREAD

**Issue by mudrd8mz** [narinkaew/moodle-local_innoedtools#3]
It is not a good idea to use course ID numbers directly in the SQL queries! Not only it has security connotations (SQL injection) but it can easily break the whole query if the ID number contains various characters like dashes or spaces:

![image](https://cloud.githubusercontent.com/assets/85831/23714313/041ec8c2-0429-11e7-8212-7250e80c4f8c.png)

**Comment by narinkaew** [comment]
Fixed, latest commits on May 20, 2017. 
https://github.com/narinkaew/moodle-local_innoedtools/commit/094fb98931f17e97364b7c73aa46e81527204a32

- Using ? parameter in query
