### ISSUE TITLE
Inno Smart Report throws error on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [narinkaew/moodle-local_innoedtools#5]
```
Debug info: ERROR: syntax error at or near "$1"
LINE 2: COALESCE(SUM(col1), 0) AS $1
^
SELECT rawname, 
COALESCE(SUM(col1), 0) AS $1 
FROM 
...
```

Stack trace:
* line 479 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 250 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 800 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 87 of /local/innoedtools/attributes/report_tag_by_overall.php: call to pgsql_native_moodle_database->get_records_sql()
* line 106 of /local/innoedtools/attributes/index.php: call to report_tag_by_overall->generate_report()

**Comment by narinkaew** [comment]
May I ask how i can test on PostgreSQL?

**Comment by mudrd8mz** [comment]
May I ask how do you test on MySQL?

**Comment by mudrd8mz** [comment]
I mean, there is nothing special about testing it there. Just install PostgreSQL into your dev environment and make sure that all the plugin's features work well there as well.

**Comment by narinkaew** [comment]
Thank you for your suggestion. I installed PostgreSQL and found the same error. I'm trying to fix this but still have no idea why is error on PostgreSQL but not MySQL.

Could you please suggest me?

**Comment by narinkaew** [comment]
I found the solution of the issue and update version to re-approval
- Fix query to support PostgreSQL & mySQL
